# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`Type-Tiny-XS`
	:runtime-requirement    [ :on "perl 5.010001"^^:CpanId ];
	:test-requirement       [ :on "Test::More 0.92"^^:CpanId ];
	.

