# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`Type-Tiny-XS`
	:configure-requirement  [ :on "ExtUtils::MakeMaker 6.58"^^:CpanId ];
	:build-requirement      [ :on "ExtUtils::ParseXS 3.16"^^:CpanId ];
	:runtime-requirement    [ :on "perl 5.008005"^^:CpanId ];
	:runtime-suggestion     [ :on "Type::Parser"^^:CpanId ];
	:test-requirement       [ :on "Test::More 0.92"^^:CpanId ];
	.

